apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hyperdx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  sources:
    - repoURL: https://hyperdxio.github.io/helm-charts
      chart: hdx-oss-v2
      targetRevision: 0.8.4
      helm:
        valueFiles:
          - $values/okd-services/services/hyperdx/helm/values.yaml
    - repoURL: https://github.com/cgraaaj/okd-infra-services.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hyperdx-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: https://github.com/cgraaaj/okd-infra-services.git
    targetRevision: main
    path: okd-services/services/hyperdx/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
