apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hyperdx-cgraaaj-in
  namespace: observability
spec:
  secretName: hyperdx-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: hyperdx.cgraaaj.in
  dnsNames:
    - hyperdx.cgraaaj.in
