apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-oidc
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: argocd-oidc
    creationPolicy: Owner
  data:
    - secretKey: oidc.clientSecret
      remoteRef:
        key: okd/platform/argocd/oidc
        property: client_secret
