apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: cloudflare-token-secret
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-token
      remoteRef:
        key: okd/platform/cert-manager/cloudflare
        property: api-token
