authentik:
  secret_key: "OjQKsE5jvVtPicanqA9Ccae4VSRfDUqh8gHJxk1yD/ZPwtBcSs/dP5f8ys6Z30yc"
  error_reporting:
    enabled: false
  postgresql:
    host: authentik-pg-rw
    port: 5432
    name: authentik
    user: authentik
    password: "kNmiWUEiy4y23gLYrt1SWFDi2kbNClp0"

global:
  nodeSelector:
    node-role.kubernetes.io/worker: ""

server:
  replicas: 2
  ingress:
    enabled: false
  env:
    - name: AUTHENTIK_HOST
      value: "https://auth.cgraaaj.in"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: server
                app.kubernetes.io/instance: authentik
            topologyKey: kubernetes.io/hostname

worker:
  replicas: 2
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: worker
                app.kubernetes.io/instance: authentik
            topologyKey: kubernetes.io/hostname

# Bitnami PostgreSQL subchart DISABLED — using CNPG cluster (authentik-pg-rw).
postgresql:
  enabled: false
