apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: litellm-cgraaaj-in
  namespace: llm
spec:
  secretName: litellm-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: litellm.cgraaaj.in
  dnsNames:
    - litellm.cgraaaj.in
