apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-cgraaaj-in
  namespace: authentik
spec:
  secretName: authentik-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: auth.cgraaaj.in
  dnsNames:
    - auth.cgraaaj.in
